export const countries = [
    "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia",
    "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin",
    "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi",
    "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia",
    "Comoros", "Congo", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica",
    "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia",
    "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea",
    "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland",
    "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Korea, North", "Korea, South",
    "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania",
    "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius",
    "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia",
    "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Macedonia", "Norway", "Oman",
    "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal",
    "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa",
    "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore",
    "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka", "Sudan",
    "Suriname", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo",
    "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates",
    "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Yemen",
    "Zambia", "Zimbabwe"
];

export const neighborhoods = [
    "Rogers Park", "West Ridge", "Uptown", "Lincoln Square", "North Center",
    "Lake View", "Lincoln Park", "Near North Side", "Edison Park", "Norwood Park",
    "Jefferson Park", "Forest Glen", "North Park", "Albany Park", "Portage Park",
    "Irving Park", "Dunning", "Montclare", "Belmont Cragin", "Hermosa",
    "Avondale", "Logan Square", "Humboldt Park", "West Town", "Austin",
    "West Garfield Park", "East Garfield Park", "Near West Side", "North Lawndale",
    "South Lawndale", "Lower West Side", "Loop", "Near South Side", "Armour Square",
    "Douglas", "Oakland", "Fuller Park", "Grand Boulevard", "Kenwood", "Washington Park",
    "Hyde Park", "Woodlawn", "South Shore", "Chatham", "Avalon Park", "South Chicago",
    "Burnside", "Calumet Heights", "Roseland", "Pullman", "South Deering", "East Side",
    "West Pullman", "Riverdale", "Hegewisch", "Garfield Ridge", "Archer Heights",
    "Brighton Park", "McKinley Park", "Bridgeport", "New City", "West Elsdon",
    "Gage Park", "Clearing", "West Lawn", "Chicago Lawn", "West Englewood",
    "Englewood", "Greater Grand Crossing", "Ashburn", "Auburn Gresham", "Beverly",
    "Washington Heights", "Mount Greenwood", "Morgan Park", "O'Hare", "Edgewater",
  
    "Evanston", "Skokie", "Wilmette", "Winnetka", "Northbrook", "Glenview", "Glencoe", "Lincolnwood",
    "Des Plaines", "Park Ridge", "Niles", "Morton Grove", "Buffalo Grove", "Highland Park", "Lake Forest",
    "Arlington Heights", "Mount Prospect", "Palatine", "Rolling Meadows", "Prospect Heights",
    "Schaumburg", "Elk Grove Village", "Hoffman Estates", "Itasca", "Roselle", "Streamwood",
    "Bartlett", "Hanover Park", "Carol Stream", "Addison", "Bensenville", "Elmhurst", "Lombard",
    "Villa Park", "Oak Brook", "Downers Grove", "Lisle", "Naperville", "Wheaton", "Glen Ellyn",
    "Westmont", "Darien", "Willowbrook", "Woodridge", "Bolingbrook", "Plainfield", "Romeoville",
    "Lockport", "Homer Glen", "Lemont", "New Lenox", "Frankfort", "Mokena", "Orland Park",
    "Orland Hills", "Tinley Park", "Oak Lawn", "Evergreen Park", "Burbank", "Bridgeview",
    "Justice", "Summit", "Stickney", "Forest View", "Lyons", "Brookfield", "La Grange",
    "La Grange Park", "Western Springs", "Hinsdale", "Clarendon Hills", "Burr Ridge",
    "Berwyn", "Cicero", "Maywood", "Bellwood", "Broadview", "Melrose Park", "River Grove",
    "River Forest", "Forest Park", "North Riverside", "Riverside", "Chicago Ridge", "Hometown",
    "Alsip", "Midlothian", "Crestwood", "Blue Island", "Calumet Park", "Robbins", "Posen",
    "Markham", "Harvey", "Dixmoor", "Phoenix", "South Holland", "Dolton", "Calumet City",
    "Lansing", "Homewood", "Flossmoor", "Olympia Fields", "Matteson", "Country Club Hills",
    "Hazel Crest", "East Hazel Crest", "Glenwood", "Chicago Heights", "Park Forest", "Steger",
    "University Park", "Crete", "Beecher", "Monee", "Peotone", "Manhattan", "Joliet", "Shorewood"
  ];